### ISSUE TITLE
U.S.C. 50

### ISSUE THREAD

**Issue by UnitedStatesofamerica23** [usgpo/link-service#19] opened 2022-10-22 20:20 UTC

**Comment by jonb665** [comment] 2022-11-25 03:13
No one assigned

> need help

**Comment by jonquandt** [comment] 2022-11-25 12:50
@UnitedStatesofamerica23 or @jonb665  -- can you provide details of what the issue is? There is currently no description in the original request.

**Comment by jonb665** [comment] 2022-12-01 17:53
Not really sure but a little help on where to begin would be great @UnitedStatesofamerica23

**Comment by jonquandt** [comment] 2022-12-15 03:29
Closing due to no additional feedback from original requester.

**Closed by jonquandt** 2022-12-15 03:29 UTC
Labels: question
